export const PAPERS = [
  {
    title: 'Artificial Intelligence',
    list: [
      'Intelligent multi-Agent Systems',
      'Planning and Decision Support Systems',
      'Big Data Analytics',
      'Case-based Reasoning',
      'Evolutionary Computing',
      'Information Retrieval ',
      'Soft Computing ',
      'Machine Learning and Deep Learning ',
      'Computer vision',
      'Natural Language Processing, Speech and Text processing',
      'Robotics',
      'Social Network Analysis ',
      'AI and Cyber security',
      'Cognitive Science',
      'AI and its applications',
    ],
  },
  {
    title: 'Quantum Computing',
    list: [
      'Quantum error correction and fault tolerance',
      'Quantum complexity',
      'Quantum algorithms',
      'Quantum information theory',
      'Spin-based quantum information processing',
      'Nano-electronics based quantum information processing',
      'Optical quantum information processing',
      'Quantum cryptography',
      'Ultracold atoms and trapped ions',
    ],
  },
  {
    title: 'AR/VR',
    list: [
      'AR/VR and its applications',
      'Metaverse',
      'Immersive Analytics',
      'Handheld Augmented Reality',
      'Human Cognitive Processing',
      'Security and Privacy in AR/VR',
      'Information Visualization',
      'Context Awareness',
      'AR/VR in 5G networks',
      'Challenges of augmented reality',
    ],
  },
  {
    title: 'IoT Technologies and applications',
    list: [
      '5G/6G Networks and IoT',
      'IoT Interoperability and Multi-Platform Integration',
      'IoT architecture, protocols and Standards',
      'Wireless Sensor Network for IoT',
      'Software Defined Network',
      'Sensors Data Management, IoT Mining and Analytics',
      'Big Data and Information Integrity in IoT',
      'IoT Security and Trust ',
      'Communication Security in IoT',
      'Heterogeneous Networks, Web of Things, Web of Everything',
      'Internet of Nano Things',
      'Industrial IoT and Factory of Things ',
      'Green IoT',
      'IoT and block chain',
      'IoT applications for smart systems',
    ],
  }
];
