export const LINKS = [
  // { name: 'Home', href: 'home' },
  { name: 'Conference', href: 'conference' },
  { name: 'About Us', href: 'about-us' },
  { name: 'Call for Paper', href: 'callforpaper' },
  { name: 'Important Dates', href: 'important_dates' },
  { name: 'For Authors', href: 'authors' },
  { name: 'Committee', href: 'committee' },
  // { name: 'Submission', href: 'submission' },
  // { name: 'Pre-conf Workshop', href: 'workshop' },
  // { name: 'Speakers', href: 'speakers' },
  // { name: 'Registration', href: 'registration' },
  // { name: 'Payment', href: 'payment' },
  { name: 'Contact', href: 'contact' },
  { name: 'History', href: 'archive' },
];
